<a href="https://colab.research.google.com/github/gkothari25/object_classification/blob/master/OR_gate_using_PLL.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [42]:
import numpy as np

i_vector = np.array([[0,0,1,1],[0,1,0,1]])
wt_vector = np.zeros(i_vector.shape)
out_vector = np.array([[0,1,1,1]])
print(i_vector)
print(wt_vector)
print(out_vector)

print(wt_vector[0])


[[0 0 1 1]
 [0 1 0 1]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[0 1 1 1]]
[0. 0. 0. 0.]


In [57]:
#y_pred = wt*x
epoch = 10
for k in range(epoch):
   
  for i,l in enumerate(zip(np.transpose(i_vector),np.transpose(wt_vector),np.transpose(out_vector))):
    #pred_scaler = np.matmul(np.transpose(wt_vector),i_vector)
    j = list(l)
    pred_scaler = np.matmul(j[0],np.transpose(j[1]))
    #print(pred_scaler)
    if pred_scaler < 0: 
      if j[2] == 1:
        j[1]= np.add(j[1],j[0])
        #print(j[1])
    
    elif pred_scaler >= 0: 
        if j[2] == 0:
          j[1] = np.subtract(j[1],j[0])
          print(j[1])
    




[0. 0.]
[0. 0.]
[0. 0.]
[0. 0.]
[0. 0.]
[0. 0.]
[0. 0.]
[0. 0.]
[0. 0.]
[0. 0.]


In [44]:
print(wt_vector)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]
